export type TextFieldTypes =
  | "text"
  | "email"
  | "password"
  | "search"
  | "cpf"
  | "cnpj"
  | "cpfcnpj"
  | "phone"
  | "cep"
  | "currency"
  | "percent"
  | "username"
  | "number"; // ajustar;
// | "url"
// | "textarea"
// | "richtext" // WYSIWYG (Markdown / HTML)
// | "code" // JSON, SQL, código
// | "slug" // gera slug automaticamente

export type NumberFieldTypes =
  | "number"
  | "stepper"
  | "num_currency" // Ajustar
  | "num_percent"; // Ajustar
//   | "ranger" // slider
//   | "rating" // estrelas, pontos
//   | "otp"; // pininput múltiplos campos

export type DateFieldTypes =
  | "date"
  | "datetime"
  | "month"
  | "year"
  | "week"
  | "quarter"
  | "time"
  | "hour"
  | "minute"
  | "second"
  | "daterange" 
  | "datetimerange"
  | "timerange";
//   | "calendar"; //input;

// export type SelectFieldTypes =
//   | "select" // dropdown // variações comumns (com busca, assíncrono, com criação (createble), hierárquico)
//   | "radiogroup"
//   | "segmentedcontrol"
//   | "toggle" // switch
//   | "multiselect"
//   | "checkboxgroup"
//   | "tagselect"
//   | "transferlist";

// export type OthersFieldTypes =
//   | "cascader"
//   | "treeselect"
//   | "autocomplete"
//   | "mention";

// export type BooleanFieldTypes =
//   | "checkbox"
//   | "switch"
//   | "toggle" // sim e nao
//   | "booleanbuttongroup";

// export type FileFieldTypes =
//   | "file"
//   | "image"
//   | "video"
//   | "audio"
//   | "dragdrop"
//   | "multifile"
//   | "avatar"
//   | "cameracapture";

// export type VisualFieldTypes =
//   | "color" // picker
//   | "icon" // picker
//   | "emoji" // picker
//   | "font" // picker
//   | "theme"; // picker

// export type LocFieldTypes =
//   | "address"
//   | "cep" // zip
//   | "map" // picker
//   | "geolocation"
//   | "cidade" // select
//   | "estado" // select
//   | "pais" // select
//   | "combo"; // contry / state / city select

// export type AuthFieldTypes =
//   | "otp" // input
//   | "biometric" // figerprint / face
//   | "captcha" // input
//   | "securityquestion";

// export type CustomFieldTypes =
//   | "moneysplit" // parcelas
//   | "stockquantity"
//   | "discount"
//   | "pricewithtax"
//   | "productselector"
//   | "userselector"
//   | "permissionsmatrix"
//   | "schedulebuilder"
//   | "jsonschemaform"
//   | "formula";

// export type InvFieldTypes =
//   | "hidden"
//   | "computed"
//   | "autogenerated"
//   | "derivedfield"
//   | "metadata"

export type BaseFieldTypes = TextFieldTypes | NumberFieldTypes | DateFieldTypes;
